spring.application.name=aula20260415

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_projeto20260415
spring.datasource.username=root
spring.datasource.password=
